name: zait_cash_portfolio
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  # sdk: 3.10.0 
  sdk: ">=3.7.0 <4.0.0"
  # sdk: 3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # architecture & state management
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  get_it: ^8.2.0
  injectable: ^2.5.1

  # data & storage
  supabase_flutter: ^2.10.1

  # ui & animations
  animations: ^2.0.11
  animated_reorderable_list: ^1.3.0
  lottie: ^3.3.1
  skeletonizer: ^2.1.0+1
  toastification: ^3.0.3
  super_sliver_list: ^0.4.1
  amazing_icons: ^2.0.0
  fl_chart: ^1.1.1
  mesh_gradient: ^1.3.8
  flutter_map: ^8.2.2

  # utilities
  intl: ^0.20.2
  after_layout: ^1.2.0
  equatable: ^2.0.7
  csv: ^6.0.0 #remove later
  url_launcher: ^6.3.1
  http: ^1.2.2

  # windows
  # window_manager: ^0.5.1
  flutter_dotenv: ^5.2.1
  latlong2: ^0.9.1
  video_player: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # architecture
  build_runner: ^2.7.1
  injectable_generator: ^2.8.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/ 
    - assets/videos/
    - assets/gifs/
    # only enable on deubg 
    # - .env

  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf